server:
  port: 8081
  servlet:
    context-path: /msconsulta

spring:
  application:
    name: ms-consulta
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
